In [1]:
import  pandas as pd

In [2]:
data=pd.read_json("News_Category_Dataset_v3.json",lines=True)

In [3]:
data.head()

,link,headline,category,short_description,authors,date
0,https://www.huffpost.com/entry/covid-boosters-...,Over 4 Million Americans Roll Up Sleeves For O...,U.S. NEWS,Health experts said it is too early to predict...,"Carla K. Johnson, AP",2022-09-23
1,https://www.huffpost.com/entry/american-airlin...,"American Airlines Flyer Charged, Banned For Li...",U.S. NEWS,He was subdued by passengers and crew when he ...,Mary Papenfuss,2022-09-23
2,https://www.huffpost.com/entry/funniest-tweets...,23 Of The Funniest Tweets About Cats And Dogs ...,COMEDY,"""Until you have a dog you don't understand wha...",Elyse Wanshel,2022-09-23
3,https://www.huffpost.com/entry/funniest-parent...,The Funniest Tweets From Parents This Week (Se...,PARENTING,"""Accidentally put grown-up toothpaste on my to...",Caroline Bologna,2022-09-23
4,https://www.huffpost.com/entry/amy-cooper-lose...,Woman Who Called Cops On Black Bird-Watcher Lo...,U.S. NEWS,Amy Cooper accused investment firm Franklin Te...,Nina Golgowski,2022-09-22

In [4]:
data.shape

(209527, 6)

In [5]:
data.columns

Index(['link', 'headline', 'category', 'short_description', 'authors', 'date'], dtype='str')

In [6]:
data=data['short_description'].sample(20000,random_state=42)

In [7]:
data.isnull().sum()

np.int64(0)

In [8]:
data.duplicated().sum()

np.int64(1994)

In [9]:
data.drop_duplicates(inplace=True)

In [10]:
data.duplicated().sum()

np.int64(0)

In [11]:
data.head()

128310    What if, in doing so, we won't just create new...
139983    It should have been a glorious week for AOL ch...
42339     A few protesters who refused to leave remained...
131494
163649    Scientists didn't know if humans played that g...
Name: short_description, dtype: str

In [12]:
data.shape

(18006,)

In [13]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [14]:
tokenizer=Tokenizer(oov_token="OOV")

In [15]:
tokenizer.fit_on_texts(data)

In [16]:
tokenizer.word_index

{'OOV': 1,
 'the': 2,
 'to': 3,
 'a': 4,
 'of': 5,
 'and': 6,
 'in': 7,
 'is': 8,
 'that': 9,
 'for': 10,
 'i': 11,
 'you': 12,
 'on': 13,
 'it': 14,
 'with': 15,
 'are': 16,
 'be': 17,
 'we': 18,
 'this': 19,
 'as': 20,
 'have': 21,
 'was': 22,
 'but': 23,
 'your': 24,
 'at': 25,
 'not': 26,
 'from': 27,
 'my': 28,
 'or': 29,
 'an': 30,
 'our': 31,
 'by': 32,
 'has': 33,
 'about': 34,
 'more': 35,
 'one': 36,
 'can': 37,
 'when': 38,
 'what': 39,
 'all': 40,
 'their': 41,
 'out': 42,
 'they': 43,
 'his': 44,
 "it's": 45,
 'new': 46,
 'will': 47,
 'if': 48,
 'he': 49,
 'who': 50,
 'time': 51,
 'up': 52,
 'so': 53,
 'her': 54,
 'just': 55,
 'like': 56,
 'people': 57,
 'do': 58,
 'how': 59,
 'been': 60,
 'some': 61,
 'there': 62,
 'said': 63,
 'no': 64,
 'me': 65,
 'than': 66,
 'most': 67,
 'us': 68,
 'year': 69,
 'day': 70,
 'get': 71,
 'after': 72,
 'would': 73,
 'many': 74,
 'make': 75,
 'into': 76,
 'she': 77,
 'had': 78,
 'know': 79,
 'first': 80,
 'over': 81,
 'these': 82,
 'years': 83,
 'life': 84,
 'were': 85,
 'way': 86,
 'now': 87,
 'them': 88,
 'may': 89,
 'world': 90,
 'want': 91,
 'even': 92,
 'could': 93,
 'its': 94,
 'which': 95,
 'other': 96,
 'much': 97,
 'two': 98,
 'trump': 99,
 'love': 100,
 'last': 101,
 'only': 102,
 'being': 103,
 "don't": 104,
 'while': 105,
 'president': 106,
 'because': 107,
 'here': 108,
 'think': 109,
 'also': 110,
 'take': 111,
 'good': 112,
 'back': 113,
 'see': 114,
 'week': 115,
 '”': 116,
 'those': 117,
 'need': 118,
 'best': 119,
 'every': 120,
 's': 121,
 'very': 122,
 'old': 123,
 'say': 124,
 'before': 125,
 'still': 126,
 'too': 127,
 'things': 128,
 'something': 129,
 'u': 130,
 'help': 131,
 'women': 132,
 'really': 133,
 'children': 134,
 'go': 135,
 'work': 136,
 'through': 137,
 'should': 138,
 'little': 139,
 'why': 140,
 'where': 141,
 'well': 142,
 'never': 143,
 'right': 144,
 'going': 145,
 'look': 146,
 'down': 147,
 'health': 148,
 'off': 149,
 'made': 150,
 'own': 151,
 "you're": 152,
 "i'm": 153,
 'long': 154,
 'around': 155,
 'says': 156,
 'home': 157,
 'great': 158,
 'any': 159,
 'better': 160,
 'feel': 161,
 'family': 162,
 'then': 163,
 'few': 164,
 'always': 165,
 'since': 166,
 'kids': 167,
 'find': 168,
 'big': 169,
 'come': 170,
 'did': 171,
 'american': 172,
 'ever': 173,
 'state': 174,
 'am': 175,
 'news': 176,
 "we're": 177,
 'show': 178,
 'change': 179,
 'him': 180,
 'between': 181,
 'during': 182,
 'another': 183,
 'both': 184,
 'check': 185,
 'days': 186,
 'part': 187,
 'often': 188,
 'white': 189,
 'keep': 190,
 'got': 191,
 'against': 192,
 'live': 193,
 'three': 194,
 'might': 195,
 'sure': 196,
 "that's": 197,
 'without': 198,
 'lot': 199,
 'care': 200,
 'comes': 201,
 'house': 202,
 'school': 203,
 'today': 204,
 'each': 205,
 'does': 206,
 'country': 207,
 "there's": 208,
 'making': 209,
 'getting': 210,
 'thing': 211,
 'same': 212,
 'again': 213,
 'found': 214,
 'real': 215,
 'place': 216,
 "doesn't": 217,
 'whether': 218,
 'lives': 219,
 'different': 220,
 "i've": 221,
 'next': 222,
 "can't": 223,
 'donald': 224,
 'yourself': 225,
 'hard': 226,
 'past': 227,
 'high': 228,
 'child': 229,
 'yet': 230,
 'important': 231,
 'black': 232,
 'end': 233,
 'food': 234,
 '10': 235,
 'told': 236,
 'city': 237,
 'former': 238,
 'give': 239,
 'man': 240,
 'let': 241,
 'video': 242,
 'national': 243,
 'facebook': 244,
 'twitter': 245,
 'called': 246,
 'enough': 247,
 'become': 248,
 'use': 249,
 'having': 250,
 'looking': 251,
 'ago': 252,
 'once': 253,
 'experience': 254,
 'york': 255,
 'huffpost': 256,
 'parents': 257,
 'style': 258,
 'moment': 259,
 'night': 260,
 'away': 261,
 'social': 262,
 'taking': 263,
 'everyone': 264,
 'star': 265,
 'read': 266,
 'americans': 267,
 'five': 268,
 'must': 269,
 'public': 270,
 'start': 271,
 'put': 272,
 'times': 273,
 'someone': 274,
 'such': 275,
 'person': 276,
 'less': 277,
 'season': 278,
 'states': 279,
 'study': 280,
 "they're": 281,
 'month': 282,
 'media': 283,
 '1': 284,
 'thought': 285,
 '000': 286,
 'mind': 287,
 'face': 288,
 'money': 289,
 'everything': 290,
 'set': 291,
 'men': 292,
 "isn't": 293,
 'others': 294,
 'woman': 295,
 'makes': 296,
 'believe': 297,
 'tell': 298,
 'top': 299,
 'ways': 300,
 'full': 301,
 'community': 302,
 'actually': 303,
 'wedding': 304,
 'together': 305,
 'story': 306,
 'four': 307,
 'took': 308,
 'friends': 309,
 'party': 310,
 'million': 311,
 'far': 312,
 'sometimes': 313,
 'used': 314,
 'according': 315,
 'free': 316,
 'summer': 317,
 'doing': 318,
 "didn't": 319,
 'working': 320,
 'body': 321,
 'below': 322,
 "we've": 323,
 'young': 324,
 'police': 325,
 'list': 326,
 'fashion': 327,
 'already': 328,
 'months': 329,
 'america': 330,
 'travel': 331,
 'perfect': 332,
 'campaign': 333,
 'government': 334,
 '—': 335,
 'across': 336,
 'though': 337,
 'favorite': 338,
 'recent': 339,
 'future': 340,
 'easy': 341,
 'left': 342,
 'stop': 343,
 'it’s': 344,
 'bad': 345,
 'age': 346,
 'least': 347,
 'heart': 348,
 'try': 349,
 'maybe': 350,
 '2': 351,
 'human': 352,
 "here's": 353,
 'means': 354,
 'until': 355,
 'cancer': 356,
 'political': 357,
 'second': 358,
 'healthy': 359,
 'job': 360,
 'behind': 361,
 'question': 362,
 'move': 363,
 'call': 364,
 'small': 365,
 'asked': 366,
 'post': 367,
 'came': 368,
 'matter': 369,
 'trying': 370,
 'talk': 371,
 'business': 372,
 'divorce': 373,
 'sleep': 374,
 'wanted': 375,
 'republican': 376,
 'support': 377,
 'nothing': 378,
 'living': 379,
 'self': 380,
 'bill': 381,
 'share': 382,
 'head': 383,
 "you've": 384,
 'percent': 385,
 'done': 386,
 'happy': 387,
 'history': 388,
 'death': 389,
 'under': 390,
 'words': 391,
 'true': 392,
 'almost': 393,
 'especially': 394,
 'mom': 395,
 'mean': 396,
 'game': 397,
 'war': 398,
 'remember': 399,
 'baby': 400,
 'case': 401,
 'seems': 402,
 'company': 403,
 'gop': 404,
 'mother': 405,
 'based': 406,
 'art': 407,
 'shows': 408,
 'fact': 409,
 'seen': 410,
 'however': 411,
 'pretty': 412,
 'rights': 413,
 'obama': 414,
 'law': 415,
 "he's": 416,
 'power': 417,
 'sense': 418,
 '5': 419,
 'group': 420,
 'anything': 421,
 'deal': 422,
 'major': 423,
 'com': 424,
 'idea': 425,
 'probably': 426,
 'myself': 427,
 'united': 428,
 'point': 429,
 'late': 430,
 'recently': 431,
 'gay': 432,
 'play': 433,
 'among': 434,
 'daily': 435,
 '20': 436,
 'photos': 437,
 'needs': 438,
 'single': 439,
 'son': 440,
 'problem': 441,
 'course': 442,
 'yes': 443,
 'energy': 444,
 'personal': 445,
 'ourselves': 446,
 'holiday': 447,
 'run': 448,
 'coming': 449,
 'film': 450,
 'hope': 451,
 'weight': 452,
 'eat': 453,
 'watch': 454,
 'latest': 455,
 'likely': 456,
 'started': 457,
 'known': 458,
 'nearly': 459,
 'relationship': 460,
 'clinton': 461,
 'name': 462,
 'beautiful': 463,
 'instead': 464,
 'wants': 465,
 'simple': 466,
 'learn': 467,
 'music': 468,
 'quite': 469,
 'several': 470,
 'climate': 471,
 "what's": 472,
 'fall': 473,
 'leave': 474,
 'wrong': 475,
 'kind': 476,
 'series': 477,
 'pinterest': 478,
 'rather': 479,
 'don’t': 480,
 'reason': 481,
 'washington': 482,
 'book': 483,
 'bring': 484,
 "won't": 485,
 'able': 486,
 'team': 487,
 'host': 488,
 'weeks': 489,
 'red': 490,
 'early': 491,
 'fun': 492,
 'water': 493,
 'including': 494,
 'girls': 495,
 'plan': 496,
 'outside': 497,
 'act': 498,
 'anyone': 499,
 'turn': 500,
 'couple': 501,
 'weekend': 502,
 'sunday': 503,
 'lost': 504,
 'possible': 505,
 "she's": 506,
 'number': 507,
 'looks': 508,
 "aren't": 509,
 'presidential': 510,
 'whole': 511,
 'order': 512,
 'feeling': 513,
 'hours': 514,
 'office': 515,
 'process': 516,
 'university': 517,
 'understand': 518,
 'marriage': 519,
 'research': 520,
 'control': 521,
 'eating': 522,
 'college': 523,
 'giving': 524,
 'republicans': 525,
 'girl': 526,
 "let's": 527,
 'hit': 528,
 'students': 529,
 'fear': 530,
 'democratic': 531,
 "you'll": 532,
 'issue': 533,
 'strong': 534,
 'friend': 535,
 'attention': 536,
 'opportunity': 537,
 'special': 538,
 'federal': 539,
 'education': 540,
 'six': 541,
 'close': 542,
 'went': 543,
 'ready': 544,
 'themselves': 545,
 'violence': 546,
 'families': 547,
 '4': 548,
 'thinking': 549,
 'morning': 550,
 'line': 551,
 'open': 552,
 'action': 553,
 'security': 554,
 'heard': 555,
 'air': 556,
 'photo': 557,
 'using': 558,
 '3': 559,
 'despite': 560,
 'hand': 561,
 'felt': 562,
 'local': 563,
 'd': 564,
 'light': 565,
 'step': 566,
 'election': 567,
 'questions': 568,
 'ask': 569,
 'bit': 570,
 'else': 571,
 'saturday': 572,
 'role': 573,
 'class': 574,
 'short': 575,
 'hair': 576,
 'taken': 577,
 '2012': 578,
 'click': 579,
 'disease': 580,
 'spring': 581,
 'create': 582,
 'changes': 583,
 'simply': 584,
 'race': 585,
 'happen': 586,
 'along': 587,
 'hear': 588,
 'goes': 589,
 'given': 590,
 'court': 591,
 'beauty': 592,
 'difficult': 593,
 'room': 594,
 'daughter': 595,
 'spent': 596,
 'common': 597,
 'stories': 598,
 'later': 599,
 'clear': 600,
 'planning': 601,
 'report': 602,
 '12': 603,
 'half': 604,
 'key': 605,
 'learned': 606,
 'break': 607,
 '30': 608,
 'career': 609,
 'benefits': 610,
 'needed': 611,
 'following': 612,
 'seem': 613,
 'biggest': 614,
 'wife': 615,
 'talking': 616,
 'tv': 617,
 'husband': 618,
 'pay': 619,
 '2013': 620,
 'lead': 621,
 '“i': 622,
 'dress': 623,
 'running': 624,
 'attack': 625,
 'word': 626,
 'perhaps': 627,
 'hot': 628,
 'side': 629,
 'saying': 630,
 'friday': 631,
 'loss': 632,
 'system': 633,
 'truth': 634,
 'culture': 635,
 'finally': 636,
 'longer': 637,
 'leaders': 638,
 'general': 639,
 'popular': 640,
 'met': 641,
 'eyes': 642,
 'gets': 643,
 'movie': 644,
 'researchers': 645,
 'died': 646,
 'south': 647,
 'hands': 648,
 'although': 649,
 'term': 650,
 'john': 651,
 'stress': 652,
 'trip': 653,
 'rest': 654,
 'treatment': 655,
 'international': 656,
 'knew': 657,
 'exactly': 658,
 'online': 659,
 'married': 660,
 'continue': 661,
 'hotel': 662,
 '2014': 663,
 'reality': 664,
 '6': 665,
 'challenge': 666,
 'decision': 667,
 'actress': 668,
 'alone': 669,
 'stand': 670,
 'moments': 671,
 'offer': 672,
 'takes': 673,
 'street': 674,
 'born': 675,
 'positive': 676,
 'upon': 677,
 'practice': 678,
 'walk': 679,
 'became': 680,
 'policy': 681,
 'pain': 682,
 'sweet': 683,
 'spend': 684,
 'impact': 685,
 'senate': 686,
 'beyond': 687,
 'democrats': 688,
 '7': 689,
 'tips': 690,
 'sex': 691,
 'financial': 692,
 'risk': 693,
 'fast': 694,
 'medical': 695,
 'soon': 696,
 'choice': 697,
 'released': 698,
 'color': 699,
 'turned': 700,
 'growing': 701,
 'north': 702,
 'amazing': 703,
 'consider': 704,
 'members': 705,
 'journey': 706,
 'either': 707,
 'lose': 708,
 'tax': 709,
 'winter': 710,
 'hold': 711,
 'issues': 712,
 'information': 713,
 'itself': 714,
 'instagram': 715,
 'middle': 716,
 'killed': 717,
 'saw': 718,
 'fight': 719,
 'society': 720,
 'began': 721,
 'safe': 722,
 'ideas': 723,
 'hillary': 724,
 'forward': 725,
 'truly': 726,
 "wasn't": 727,
 'sexual': 728,
 'global': 729,
 'within': 730,
 'internet': 731,
 'certain': 732,
 'space': 733,
 'forget': 734,
 'senator': 735,
 'event': 736,
 'ones': 737,
 'huge': 738,
 'meet': 739,
 'cannot': 740,
 'beach': 741,
 'sign': 742,
 'service': 743,
 'wrote': 744,
 'candidate': 745,
 'administration': 746,
 'debate': 747,
 'becoming': 748,
 'gift': 749,
 'companies': 750,
 'monday': 751,
 'celebrate': 752,
 'brought': 753,
 'seven': 754,
 'earlier': 755,
 'touch': 756,
 'car': 757,
 'wait': 758,
 'win': 759,
 'economy': 760,
 'march': 761,
 'countries': 762,
 'brand': 763,
 "trump's": 764,
 'july': 765,
 'visit': 766,
 'stay': 767,
 'tumblr': 768,
 'congress': 769,
 'dr': 770,
 'led': 771,
 'tuesday': 772,
 'happened': 773,
 'shot': 774,
 '15': 775,
 'inside': 776,
 'force': 777,
 'super': 778,
 'large': 779,
 'oh': 780,
 'chief': 781,
 'learning': 782,
 'c': 783,
 'director': 784,
 'rules': 785,
 'economic': 786,
 'vote': 787,
 'singer': 788,
 'choose': 789,
 'peace': 790,
 "'": 791,
 'california': 792,
 'center': 793,
 'fans': 794,
 'announced': 795,
 'female': 796,
 'justice': 797,
 'imagine': 798,
 'success': 799,
 'enjoy': 800,
 'avoid': 801,
 'model': 802,
 'difference': 803,
 "world's": 804,
 'park': 805,
 'oil': 806,
 'dinner': 807,
 'chance': 808,
 'thursday': 809,
 'michael': 810,
 'wall': 811,
 'results': 812,
 'actor': 813,
 'response': 814,
 'present': 815,
 'whatever': 816,
 'schools': 817,
 'millions': 818,
 'wear': 819,
 'building': 820,
 'whose': 821,
 'nominee': 822,
 'secret': 823,
 'gun': 824,
 'reasons': 825,
 "year's": 826,
 'industry': 827,
 'places': 828,
 'decades': 829,
 'answer': 830,
 'level': 831,
 'department': 832,
 'interview': 833,
 'works': 834,
 'published': 835,
 'dad': 836,
 'message': 837,
 'powerful': 838,
 'entire': 839,
 'non': 840,
 'reach': 841,
 'officials': 842,
 'third': 843,
 'market': 844,
 'leader': 845,
 'leading': 846,
 'technology': 847,
 'judge': 848,
 'advice': 849,
 'hate': 850,
 'mental': 851,
 'front': 852,
 'workers': 853,
 'worth': 854,
 'science': 855,
 'focus': 856,
 'fresh': 857,
 'legal': 858,
 'deep': 859,
 'low': 860,
 'completely': 861,
 'accused': 862,
 'claim': 863,
 'spending': 864,
 'loved': 865,
 'cause': 866,
 'data': 867,
 'effort': 868,
 'exercise': 869,
 'surprise': 870,
 'texas': 871,
 'press': 872,
 'voters': 873,
 'christmas': 874,
 'follow': 875,
 'expect': 876,
 'i’m': 877,
 'kid': 878,
 'co': 879,
 'movement': 880,
 'decided': 881,
 'events': 882,
 'anti': 883,
 'hospital': 884,
 'near': 885,
 '11': 886,
 'gone': 887,
 'grow': 888,
 'drug': 889,
 'current': 890,
 'above': 891,
 'military': 892,
 'parenting': 893,
 'thousands': 894,
 'attorney': 895,
 'calls': 896,
 "wouldn't": 897,
 'form': 898,
 'held': 899,
 'reports': 900,
 'nature': 901,
 'conversation': 902,
 'add': 903,
 'experiences': 904,
 'nation': 905,
 'training': 906,
 'serious': 907,
 'comments': 908,
 'crisis': 909,
 'adults': 910,
 'yoga': 911,
 '50': 912,
 'changed': 913,
 'patients': 914,
 'skin': 915,
 'land': 916,
 'kitchen': 917,
 'potential': 918,
 'plans': 919,
 'emotional': 920,
 'area': 921,
 'include': 922,
 '8': 923,
 'happens': 924,
 'unique': 925,
 "i'd": 926,
 'cost': 927,
 'wearing': 928,
 '24': 929,
 'project': 930,
 'usually': 931,
 'dog': 932,
 'record': 933,
 'view': 934,
 'david': 935,
 'london': 936,
 'certainly': 937,
 'dream': 938,
 'earth': 939,
 'rich': 940,
 'tried': 941,
 'changing': 942,
 'begin': 943,
 'allow': 944,
 'situation': 945,
 'reuters': 946,
 'plenty': 947,
 'reportedly': 948,
 '100': 949,
 'problems': 950,
 'brain': 951,
 'student': 952,
 'claims': 953,
 'extra': 954,
 'watching': 955,
 'playing': 956,
 'private': 957,
 "couldn't": 958,
 'physical': 959,
 'trust': 960,
 'moving': 961,
 'rock': 962,
 'wonder': 963,
 'finding': 964,
 'save': 965,
 'thanks': 966,
 'beginning': 967,
 'speak': 968,
 'article': 969,
 'james': 970,
 '2015': 971,
 'definitely': 972,
 'parent': 973,
 'eye': 974,
 'fox': 975,
 '9': 976,
 'return': 977,
 'himself': 978,
 'evidence': 979,
 'reported': 980,
 'paris': 981,
 'calling': 982,
 'town': 983,
 'stars': 984,
 'looked': 985,
 'god': 986,
 'guy': 987,
 "president's": 988,
 'products': 989,
 'provide': 990,
 'boys': 991,
 'dead': 992,
 '18': 993,
 'hour': 994,
 'expected': 995,
 '“the': 996,
 'foods': 997,
 'approach': 998,
 'los': 999,
 'reading': 1000,
 ...}

In [17]:
len(tokenizer.word_index)

29282

In [18]:
data=tokenizer.texts_to_sequences(data)

In [19]:
data

[[39,
  48,
  7,
  318,
  53,
  18,
  485,
  55,
  582,
  46,
  1690,
  10,
  446,
  1446,
  110,
  8479,
  300,
  3,
  582,
  46,
  1690,
  10,
  31,
  547,
  9,
  89,
  26,
  21,
  1582,
  4864],
 [14,
  138,
  21,
  60,
  4,
  4445,
  115,
  10,
  8480,
  781,
  1017,
  2785,
  7128,
  44,
  8481,
  8482,
  10762,
  795,
  809],
 [4, 164, 1966, 50, 2128, 3, 474, 2786, 25, 2, 1324, 809],
 [],
 [1286,
  319,
  79,
  48,
  1121,
  1367,
  9,
  397,
  20,
  142,
  23,
  7,
  2,
  101,
  608,
  83,
  1486,
  2940,
  184,
  1368,
  6,
  796],
 [108, 16, 268, 300, 3, 71, 61, 592, 374, 105, 4865, 4, 10763, 10, 24, 229],
 [10,
  4,
  259,
  241,
  225,
  963,
  6,
  241,
  24,
  287,
  4866,
  34,
  39,
  384,
  60,
  4,
  187,
  5,
  19,
  69,
  40,
  5,
  82,
  128,
  6,
  35,
  16,
  128,
  9,
  93,
  672,
  12,
  30,
  537,
  3,
  1487,
  24,
  1447],
 [32,
  810,
  15034,
  15035,
  3787,
  4446,
  39,
  73,
  14,
  111,
  3,
  582,
  4,
  35,
  782,
  5403,
  3109,
  39,
  2941,
  269],
 [7,
  1122,
  10764,
  10765,
  2,
  86,
  2,
  991,
  314,
  3,
  623,
  54,
  52,
  38,
  43,
  85,
  139,
  43,
  73,
  4112,
  42,
  3543],
 [38,
  11,
  22,
  4,
  878,
  701,
  52,
  7,
  482,
  564,
  783,
  182,
  2,
  6135,
  28,
  98,
  338,
  828,
  3,
  766,
  85,
  2,
  15036,
  6],
 [49, 63, 19, 176, 8, 7, 4, 220, 2641],
 [15037,
  6,
  15038,
  263,
  2129,
  5,
  19,
  415,
  7,
  6136,
  22,
  28,
  423,
  1967,
  6137,
  8483,
  63],
 [964,
  300,
  3,
  131,
  965,
  13,
  24,
  952,
  4867,
  7129,
  37,
  965,
  4,
  199,
  5,
  51,
  6,
  652,
  38,
  4868,
  24,
  952,
  5404,
  111,
  2,
  51,
  3,
  7130,
  82,
  2642,
  6138,
  7129,
  1817],
 [45,
  3788,
  2,
  80,
  51,
  9,
  61,
  1018,
  29,
  1018,
  1488,
  7,
  702,
  2050,
  33,
  1818,
  1448,
  15,
  94,
  1691,
  2942,
  10766,
  7131,
  2,
  5405,
  398,
  8,
  2,
  15039,
  5,
  2,
  859,
  8484,
  6139,
  15040,
  6,
  7132,
  197,
  6140,
  3789,
  181,
  2,
  130,
  121,
  6,
  702,
  2050,
  10,
  829],
 [164,
  57,
  91,
  3,
  71,
  1325,
  14,
  37,
  17,
  2527,
  593,
  6,
  1216,
  20,
  4,
  1019,
  30,
  3110,
  1287,
  5,
  132,
  1093,
  7,
  3544,
  9,
  16,
  5406,
  6,
  92,
  2051,
  13,
  8485],
 [2,
  1038,
  57,
  4113,
  7133,
  212,
  691,
  519,
  6,
  377,
  10,
  2,
  144,
  5,
  660,
  432,
  6,
  2337,
  1094,
  3,
  3790,
  134,
  4447,
  55,
  3316,
  5,
  912,
  385,
  23,
  2,
  1449,
  10,
  1819,
  7,
  2528,
  33,
  30,
  2787,
  15041],
 [966,
  3,
  2,
  520,
  5,
  15042,
  6,
  294,
  411,
  18,
  16,
  967,
  3,
  1255,
  9,
  74,
  5,
  31,
  1583,
  6141,
  34,
  1584,
  16,
  992,
  475,
  353,
  39,
  177,
  782],
 [106,
  1178,
  1410,
  6,
  5407,
  3791,
  47,
  968,
  809,
  20,
  2,
  1288,
  845,
  33,
  1747,
  52,
  44,
  2416,
  10,
  554,
  15043,
  7,
  2052,
  1217],
 [14, 673, 4, 538, 476, 5, 526, 3, 2643, 4, 8486, 4114, 2529],
 [18, 40, 1585, 4, 139, 2644, 15, 31, 1692],
 [2,
  539,
  7134,
  811,
  674,
  15044,
  47,
  161,
  2,
  7135,
  5,
  15045,
  48,
  482,
  1289,
  740,
  2130],
 [98, 8487, 21, 60, 1636, 7, 1256, 15, 2, 2053],
 [224,
  99,
  33,
  4,
  496,
  1290,
  48,
  416,
  1748,
  15,
  4,
  10767,
  2229,
  6,
  14,
  2054,
  2,
  1155,
  5,
  497,
  1156,
  9,
  416],
 [20,
  187,
  5,
  31,
  6142,
  162,
  631,
  477,
  205,
  115,
  177,
  15046,
  4,
  220,
  15047,
  3,
  467,
  59,
  43,
  2645],
 [10768,
  4869,
  15048,
  5408,
  210,
  76,
  2131,
  20,
  4,
  878,
  616,
  3,
  3111,
  6,
  39,
  14,
  354,
  3,
  17,
  172],
 [114,
  10769,
  15049,
  258,
  137,
  2,
  83,
  636,
  4,
  2230,
  7136,
  177,
  4115,
  1450,
  34,
  53,
  39,
  206,
  14,
  111],
 [10770,
  10771,
  42,
  94,
  496,
  3,
  1123,
  2,
  1968,
  5409,
  10,
  1218,
  10772,
  2231,
  3792],
 [315,
  3,
  334,
  4870,
  13,
  8488,
  1451,
  2055,
  3545,
  16,
  361,
  993,
  385,
  5,
  130,
  121,
  3546,
  1326,
  2056],
 [27,
  4448,
  15050,
  2646,
  5410,
  10,
  54,
  1039,
  15051,
  3,
  10773,
  15052,
  386,
  52,
  20,
  6143,
  10774,
  353,
  2417,
  9,
  169,
  3793,
  169,
  3547,
  10775,
  6,
  169,
  1969,
  1489,
  8489,
  61,
  726,
  703,
  6,
  7137,
  2943,
  812],
 [64,
  369,
  59,
  617,
  33,
  913,
  6,
  47,
  179,
  213,
  81,
  2,
  83,
  48,
  62,
  8,
  4,
  6144,
  9,
  33,
  64,
  118,
  3,
  8490,
  714,
  9,
  6144,
  8,
  1257,
  2,
  102,
  211,
  9,
  4,
  112,
  1257,
  133,
  438,
  8,
  4,
  365,
  4116,
  594,
  301,
  5,
  158,
  6,
  8491,
  2647],
 [4,
  2418,
  10,
  1586,
  1179,
  8492,
  63,
  4871,
  57,
  1749,
  132,
  6,
  134,
  85,
  2232,
  32,
  2,
  1970,
  7,
  15053],
 [19,
  969,
  80,
  1541,
  13,
  8493,
  424,
  4448,
  15054,
  8,
  1750,
  15055,
  784,
  5,
  1750,
  540,
  846,
  2],
 [411,
  48,
  15056,
  5411,
  16,
  133,
  24,
  211,
  12,
  37,
  71,
  24,
  151,
  7138,
  15057,
  10,
  55,
  10776,
  4117,
  47,
  12,
  1180,
  36],
 [2,
  1751,
  1971,
  2,
  10777,
  5,
  46,
  130,
  121,
  7139,
  785,
  13,
  751,
  2648,
  25,
  10778,
  275,
  2132],
 [15058,
  6145,
  1258,
  335,
  30,
  6145,
  2338,
  1820,
  1972,
  8,
  1752,
  4,
  3794,
  122,
  270,
  2338,
  25,
  30,
  6145,
  1973],
 [71, 24, 3112, 13],
 [2,
  4118,
  3,
  2,
  2944,
  5412,
  930,
  8,
  2788,
  3,
  17,
  2,
  1369,
  4118,
  3,
  159,
  1181,
  5,
  94,
  476],
 [1821,
  8,
  243,
  1542,
  282,
  527,
  752,
  2,
  4119,
  19,
  8494,
  3113,
  33,
  150,
  3,
  172,
  3317],
 [11,
  704,
  427,
  1891,
  1291,
  3,
  17,
  486,
  3,
  453,
  25,
  228,
  574,
  2419,
  3318,
  7,
  2,
  811,
  8495,
  6,
  1693,
  7,
  181,
  13,
  4,
  1124,
  2133,
  6,
  3,
  2,
  8496,
  8497,
  5,
  28,
  692,
  3795],
 [2,
  106,
  1411,
  4120,
  5413,
  15059,
  1892,
  15060,
  138,
  21,
  753,
  8498,
  5414,
  4449,
  3,
  797,
  3796],
 [49, 4872, 7, 13, 970, 15061, 8499, 105, 1020, 15, 5415, 10779],
 [2, 813, 2134, 13, 44, 1062, 2789, 15, 784, 15062, 1893],
 [1452,
  1370,
  2,
  3319,
  63,
  94,
  1021,
  5,
  9,
  1968,
  6,
  2,
  98,
  50,
  1125,
  2,
  348,
  889,
  182,
  2339,
  22,
  1974],
 [48,
  12,
  21,
  60,
  5416,
  3,
  24,
  609,
  10780,
  10,
  74,
  83,
  12,
  47,
  17,
  486,
  3,
  766,
  24,
  609,
  3114,
  7,
  565,
  5,
  19,
  46,
  4121,
  1894,
  39,
  13,
  2,
  3114,
  126,
  6146,
  15,
  12,
  6,
  39,
  217,
  92,
  1822,
  583,
  47,
  1412,
  61,
  2941,
  5,
  24,
  123,
  84,
  76,
  2,
  46,
  6,
  8500,
  4,
  46,
  442],
 [264, 33, 41, 447, 2340, 15063],
 [541,
  83,
  252,
  2,
  10781,
  1543,
  52,
  41,
  278,
  25,
  1219,
  1220,
  8501,
  192,
  2,
  5417,
  14,
  22,
  110,
  751,
  260,
  1182],
 [32,
  2,
  51,
  1544,
  3548,
  155,
  2420,
  271,
  2341,
  61,
  15064,
  637,
  3549,
  205,
  502,
  3,
  1126,
  52,
  44,
  10782,
  416,
  1752,
  3,
  448,
  56,
  4,
  5418,
  4450,
  94,
  7140,
  81,
  154,
  6147,
  1975,
  341,
  6,
  1968,
  355,
  2,
  233],
 [24, 10783, 10784, 10, 3797, 8, 2, 101, 211, 12, 138, 1823],
 [2,
  8502,
  3320,
  1221,
  3,
  2,
  786,
  15065,
  33,
  342,
  74,
  8503,
  1545,
  2945,
  2530,
  92,
  72,
  43,
  2790,
  4,
  202,
  7,
  4,
  8502,
  29,
  575,
  1824,
  29,
  36,
  9,
  8,
  8504,
  53,
  43,
  3115,
  139,
  378,
  29,
  2790,
  2,
  157,
  25,
  4,
  632],
 [2,
  890,
  2649,
  346,
  10,
  301,
  262,
  554,
  610,
  8,
  6148,
  10,
  57,
  675,
  7,
  10785,
  6,
  72],
 [3321,
  15066,
  52,
  3,
  4122,
  116,
  7,
  2,
  642,
  5,
  46,
  255,
  7141,
  2233,
  2421,
  4,
  10786,
  1371,
  953,
  9,
  3321],
 [48,
  2,
  830,
  8,
  443,
  1063,
  12,
  10,
  263,
  2,
  80,
  566,
  2422,
  379,
  213,
  23,
  59,
  93,
  11,
  100,
  213,
  6,
  161,
  1453],
 [15067,
  15068,
  15069,
  4873,
  15070,
  15071,
  15072,
  971,
  6149,
  15073,
  15074,
  57,
  15,
  565,
  2650,
  642,
  89,
  21,
  4,
  1157],
 [4451,
  7142,
  6,
  715,
  8505,
  127,
  71,
  35,
  5419,
  108,
  1064,
  8506,
  75,
  2,
  307,
  994,
  6150,
  3,
  8505,
  10,
  2],
 [64, 8507, 22, 1040],
 [177,
  26,
  55,
  4,
  2057,
  177,
  30,
  4874,
  4875,
  63,
  1327,
  2531,
  879,
  2423,
  6,
  6151,
  25,
  10787,
  880,
  4,
  5420],
 [847,
  8,
  108,
  3,
  767,
  140,
  26,
  1490,
  14,
  6,
  249,
  14,
  3,
  1123,
  31,
  1637,
  5,
  2234,
  18,
  37,
  58,
  19,
  32,
  10788,
  76,
  31,
  2532,
  31,
  1022,
  6,
  7143,
  15075,
  19,
  4123,
  68,
  79,
  59,
  18,
  16,
  10789,
  3,
  847,
  7,
  2,
  259],
 [2,
  1183,
  265,
  37,
  661,
  3,
  15076,
  54,
  3798,
  5421,
  15,
  54,
  2791,
  6,
  6152,
  468,
  2342],
 [21,
  129,
  3,
  124,
  185,
  42,
  256,
  157,
  13,
  245,
  244,
  478,
  768,
  6,
  715,
  19,
  439,
  831],
 [7144,
  2533,
  2534,
  2,
  5422,
  67,
  1753,
  1454,
  4,
  716,
  7145,
  3799,
  2424,
  952,
  25,
  2,
  260,
  203,
  5423],
 [4124,
  18,
  79,
  45,
  503,
  23,
  35,
  3116,
  45,
  70,
  548,
  5,
  46,
  255,
  327,
  115,
  48,
  152,
  250,
  4,
  226,
  51,
  1095],
 [49, 55, 3322, 77, 73, 343, 6153],
 [2,
  4876,
  7,
  781,
  4452,
  7,
  6,
  42,
  5,
  2792,
  336,
  2,
  2135,
  23,
  102,
  4,
  164,
  15077,
  3550,
  21,
  150,
  2,
  189,
  202,
  1694,
  3800,
  1976,
  185,
  42,
  82,
  1328,
  1895,
  1096,
  10,
  4,
  106],
 [15078,
  4453,
  576,
  1259,
  8508,
  6,
  8509,
  16,
  469,
  4,
  312,
  3323,
  27,
  15079,
  860,
  6154,
  6155,
  39,
  73,
  6156,
  109],
 [77,
  156,
  41,
  595,
  5424,
  643,
  14,
  861,
  38,
  12,
  21,
  35,
  57,
  7,
  2,
  162,
  62,
  8,
  9,
  74,
  35,
  57],
 [36, 169, 362, 8, 59, 97, 3117, 4125, 47, 369],
 [931,
  45,
  4,
  112,
  211,
  38,
  4,
  487,
  4454,
  4,
  8510,
  23,
  727,
  2,
  401,
  38,
  2,
  10790,
  7146,
  4,
  8510,
  27,
  5417,
  15080],
 [106,
  224,
  99,
  6,
  238,
  1491,
  1290,
  11,
  781,
  970,
  6157,
  2343,
  19,
  115,
  7,
  30,
  3118,
  397,
  5,
  5425,
  5425,
  29,
  35],
 [253,
  43,
  5426,
  8511,
  2,
  754,
  10791,
  5427,
  1041,
  1895,
  2535,
  184,
  3324,
  6,
  6158,
  3,
  2,
  15081,
  15082,
  5,
  2,
  1492,
  4455,
  8512,
  41,
  6159,
  1896,
  5,
  10792,
  2793,
  3325,
  2536,
  32,
  15083,
  5,
  2535,
  44,
  29,
  54,
  15084,
  15085,
  3325,
  3,
  44,
  29,
  54,
  10793,
  8513,
  3801],
 [101,
  115,
  531,
  638,
  7,
  769,
  15086,
  15,
  106,
  99,
  3,
  1825,
  9,
  31,
  334,
  7147,
  1329,
  3802],
 [323,
  214,
  268,
  5,
  2,
  119,
  662,
  1065,
  2235,
  336,
  2,
  279,
  53,
  12,
  37,
  71,
  9,
  15087,
  12,
  118,
  198,
  250,
  3,
  474,
  24,
  662],
 [45, 126, 4, 158, 363, 337],
 [8,
  14,
  8514,
  3,
  798,
  9,
  4,
  229,
  29,
  134,
  7,
  36,
  187,
  5,
  2,
  90,
  89,
  17,
  1066,
  584,
  107,
  36,
  276,
  7,
  183,
  187,
  5,
  2,
  90,
  881,
  3,
  448,
  4,
  164,
  1127],
 [38,
  152,
  10794,
  42,
  226,
  2236,
  2794,
  10,
  24,
  662,
  594,
  45,
  1097,
  38,
  2,
  662,
  10795,
  9,
  6,
  4877,
  7,
  61,
  3803,
  55,
  107],
 [11,
  314,
  3,
  146,
  25,
  57,
  56,
  9,
  15,
  4,
  10796,
  5,
  15088,
  6,
  10797,
  163,
  36,
  70,
  11,
  366,
  427,
  39,
  16,
  43,
  318,
  9,
  8,
  220],
 [4126, 78, 60, 862, 5, 6160, 1184, 3804, 27, 15089],
 [2,
  3805,
  78,
  5428,
  15090,
  1546,
  554,
  20,
  4,
  814,
  3,
  2795,
  46,
  2651,
  1638,
  3,
  1695,
  1158,
  1292,
  13,
  2,
  863],
 [10798,
  269,
  17,
  98,
  128,
  2652,
  6,
  3551,
  159,
  123,
  653,
  3,
  2,
  741,
  8,
  584,
  26,
  145,
  3,
  10799,
  10,
  4,
  5429,
  367,
  15091,
  2537],
 [218,
  152,
  1041,
  15,
  2796,
  162,
  705,
  29,
  26,
  1372,
  160,
  1897,
  42,
  25,
  347,
  194,
  29,
  307,
  954,
  15092],
 [11,
  4127,
  19,
  1547,
  27,
  7148,
  214,
  7,
  28,
  10800,
  123,
  8515,
  95,
  78,
  60,
  4878,
  7,
  4,
  2237,
  10,
  470,
  83],
 [18, 3806, 31, 338, 6161, 9, 21, 40, 2, 2344, 10801, 10, 2797],
 [323,
  40,
  555,
  34,
  2,
  417,
  5,
  676,
  549,
  23,
  4456,
  13,
  2,
  176,
  6,
  532,
  114,
  2,
  90,
  402,
  3,
  2538,
  10788,
  7,
  3,
  2,
  1696,
  67,
  5,
  2,
  51,
  7149,
  2,
  112,
  1128,
  2,
  830,
  45,
  1693,
  45,
  316,
  5,
  1548,
  127],
 [14, 8, 8516, 4128, 369, 5, 270, 15093, 9, 99, 10802, 2, 8517, 488, 63],
 [30, 3326, 22, 7, 2, 15094, 10803, 25, 2, 51, 315, 3, 1587],
 [18,
  21,
  2238,
  4,
  2136,
  3,
  1826,
  1697,
  356,
  64,
  152,
  26,
  1129,
  128,
  82,
  85,
  2,
  3807,
  391,
  3119,
  32,
  770,
  15095,
  15096,
  10804,
  25,
  2,
  4129,
  2539,
  50,
  795,
  2,
  1373,
  5,
  44,
  7150,
  1697,
  356,
  2136,
  755,
  19,
  282],
 [4879,
  15097,
  7,
  4,
  602,
  10,
  15098,
  1413,
  1898,
  1098,
  89,
  17,
  3808,
  32,
  882,
  145,
  13,
  7,
  41,
  151],
 [2, 1977, 1185, 4130, 1975, 1067, 6, 4127],
 [1754, 3, 2425, 36, 8518, 15099],
 [19,
  8,
  26,
  53,
  97,
  4,
  362,
  5,
  95,
  368,
  80,
  23,
  35,
  53,
  5,
  95,
  8,
  160,
  2,
  6162,
  6163,
  29,
  2,
  3552,
  177,
  26],
 [454,
  242,
  891,
  5,
  442,
  14,
  8,
  4,
  1583,
  10805,
  5,
  8519,
  9,
  47,
  21,
  180,
  113,
  7,
  2,
  1588,
  7,
  4,
  164,
  489,
  15100],
 [2058,
  8,
  7,
  2,
  556,
  155,
  2,
  90,
  20,
  2,
  69,
  201,
  3,
  30,
  233,
  6,
  15,
  120,
  162,
  2345,
  1260,
  4457],
 [105,
  40,
  642,
  16,
  13,
  1586,
  6,
  1186,
  183,
  4131,
  8,
  263,
  216,
  7,
  6164,
  2,
  5430,
  1040,
  108,
  8,
  35,
  5,
  30,
  1187,
  66,
  4,
  892,
  8520,
  23,
  14,
  8,
  4880,
  3,
  17,
  55,
  20,
  1099],
 [19,
  317,
  11,
  21,
  596,
  35,
  514,
  66,
  11,
  200,
  3,
  1978,
  955,
  124,
  443,
  3,
  2,
  623,
  92,
  337,
  11,
  175,
  26,
  210,
  660,
  6,
  48,
  11,
  85,
  2,
  5431,
  5,
  65,
  864,
  470,
  3809,
  1589,
  13,
  4,
  623,
  8,
  412,
  15101,
  53,
  11,
  161,
  20,
  48,
  11,
  175,
  4,
  2653,
  2137,
  10,
  19,
  617,
  178,
  9,
  1979,
  155,
  7151,
  304,
  8521],
 [7, 4881, 6, 7, 148, 10, 2, 654, 5, 31, 219],
 [305,
  2,
  307,
  21,
  504,
  15102,
  1698,
  1493,
  10806,
  618,
  810,
  15103,
  8,
  147,
  3120,
  1698,
  315,
  3,
  57,
  105],
 [1218, 198, 4458, 8, 15104, 10807, 6, 15105, 3, 1414, 2, 2138, 13, 2, 4132],
 [4,
  139,
  1068,
  7,
  4,
  7152,
  2239,
  4,
  1130,
  2529,
  6,
  3327,
  4882,
  1755,
  8522,
  155,
  44,
  8523,
  956,
  15,
  4,
  2798,
  1980],
 [4, 539, 848, 63, 15106, 3121, 85, 30, 533, 5, 505, 80, 1981, 7153],
 [4883,
  15,
  1756,
  37,
  17,
  4,
  199,
  35,
  1982,
  66,
  4883,
  15,
  57,
  6,
  14,
  673,
  4,
  199,
  35,
  4133,
  66,
  36,
  195,
  109,
  36,
  465,
  14,
  3,
  135,
  142,
  53,
  36,
  37,
  143,
  17,
  2426,
  247],
 [38,
  12,
  146,
  25,
  61,
  5,
  2,
  2540,
  31,
  1639,
  16,
  4459,
  15,
  2,
  2338,
  1640,
  14,
  55,
  8,
  597,
  418,
  156,
  1494,
  7154,
  4884,
  1549,
  8524],
 [1159,
  3,
  2,
  256,
  1757,
  550,
  15107,
  4,
  575,
  4134,
  52,
  5,
  2,
  176,
  3,
  131,
  12,
  271,
  24,
  70],
 [224,
  99,
  246,
  290,
  49,
  171,
  27,
  44,
  567,
  3,
  44,
  1184,
  2132,
  1827,
  23,
  44,
  101,
  329,
  7,
  515,
  636,
  75,
  9,
  863,
  4885],
 [15108],
 [15,
  2,
  883,
  2541,
  3122,
  449,
  27,
  2,
  99,
  8525,
  832,
  5,
  797,
  12,
  58,
  21,
  3,
  963,
  39,
  2,
  392,
  3810,
  8,
  108,
  116],
 [2, 401, 2654, 4, 2240, 5, 728, 1415, 25, 2, 6159, 203],
 [2,
  1222,
  2946,
  514,
  72,
  5432,
  717,
  98,
  57,
  7,
  4,
  2241,
  2655,
  7,
  2,
  212,
  1899],
 [4886,
  8,
  4,
  162,
  450,
  6,
  14,
  8,
  40,
  34,
  2,
  932,
  19,
  644,
  1758,
  7,
  4,
  154,
  551,
  5,
  932,
  2059,
  275,
  20,
  15109,
  4,
  932,
  5,
  15110,
  123,
  15111,
  15112,
  7155,
  7155,
  6,
  74,
  74,
  35,
  38,
  12,
  216,
  2,
  2542,
  10808,
  13,
  4,
  307,
  10809,
  10810,
  5433,
  50,
  15113,
  163,
  12,
  79,
  2346,
  16,
  112,
  12,
  21,
  225,
  4,
  528],
 [7,
  4,
  339,
  5434,
  7,
  4,
  46,
  255,
  273,
  2543,
  4135,
  6165,
  3,
  28,
  4887,
  957,
  219,
  4,
  295,
  2427,
  54,
  10811],
 [97,
  33,
  60,
  150,
  5,
  2,
  15114,
  5,
  4888,
  6166,
  6,
  1699,
  15115,
  419,
  69,
  519,
  23,
  122,
  164,
  6167,
  15116,
  14,
  195],
 [3,
  131,
  4,
  1968,
  371,
  3,
  54,
  1900,
  34,
  54,
  148,
  6,
  693,
  5,
  4889,
  221,
  10812,
  2,
  849,
  5,
  10813,
  3811,
  15117],
 [256,
  193,
  47,
  17,
  263,
  4,
  3553,
  146,
  25,
  2,
  15118,
  5,
  1759,
  7,
  330,
  4890,
  3123,
  6,
  3328,
  419,
  27,
  603,
  548],
 [253,
  213,
  2428,
  193,
  881,
  9,
  48,
  4136,
  240,
  1367,
  3329,
  15,
  61,
  237,
  167,
  10814,
  17,
  4,
  3330,
  1416,
  39],
 [2,
  1449,
  10,
  270,
  3812,
  8,
  187,
  5,
  6168,
  1760,
  4891,
  5414,
  15119,
  3124,
  3813,
  5,
  786,
  6,
  262,
  4137],
 [91,
  35,
  17,
  196,
  3,
  185,
  42,
  256,
  258,
  13,
  245,
  244,
  768,
  478,
  6,
  715,
  25,
  2429,
  114],
 [87, 506, 2242, 1550, 4, 298, 40, 483, 34, 14],
 [48, 12, 37, 364, 10815, 44, 46, 662, 8526],
 [2243,
  1258,
  2,
  2947,
  2544,
  5,
  847,
  795,
  4,
  268,
  69,
  496,
  1042,
  3,
  3125,
  471,
  179,
  23],
 [19, 8, 59, 264, 138, 833, 2, 106],
 [99, 8, 995, 3, 8527, 742, 2, 2060, 76, 415],
 [2,
  6169,
  6170,
  2061,
  5435,
  4,
  933,
  507,
  5,
  1828,
  477,
  15120,
  10,
  4,
  7156,
  178],
 [49, 2430, 2, 585, 89, 419],
 [48,
  12,
  56,
  2,
  444,
  1829,
  610,
  5,
  4,
  15121,
  23,
  476,
  5,
  850,
  2,
  565,
  15122,
  27,
  2,
  15123,
  18,
  815,
  12,
  15,
  4],
 [15124,
  20,
  15125,
  134,
  1638,
  3,
  17,
  35,
  25,
  693,
  10,
  1641,
  32,
  2244,
  7157,
  62,
  16,
  98,
  220,
  2245],
 [3331,
  1069,
  402,
  3,
  21,
  393,
  290,
  162,
  3126,
  6,
  799,
  23,
  92,
  2,
  2139,
  33,
  3127,
  6,
  1901],
 [1188,
  32,
  1131,
  487,
  4892,
  15126,
  6,
  3332,
  15127,
  5,
  6171,
  6,
  2431,
  2,
  256,
  193,
  291,
  6172,
  4,
  1330],
 [222,
  266,
  2,
  154,
  1969,
  32,
  15128,
  15129,
  6,
  2785,
  1824,
  14,
  8,
  28,
  338,
  4893,
  306,
  6,
  14,
  33,
  2236,
  1070,
  1642],
 [374,
  4894,
  8,
  26,
  55,
  4,
  1368,
  1983,
  132,
  394,
  117,
  15,
  10816,
  6,
  29,
  2347,
  118,
  3,
  1132,
  52,
  3,
  2,
  6173,
  5,
  10817,
  6,
  1551,
  655,
  48,
  1984,
  15,
  14],
 [2,
  280,
  2246,
  25,
  2,
  172,
  4460,
  15130,
  656,
  4460,
  1590,
  663,
  1455,
  15131,
  57,
  15],
 [15132, 15133, 47, 17, 2, 102, 1223, 1761, 2545, 7158, 44, 207, 7, 4138],
 [13,
  2,
  70,
  5,
  15134,
  705,
  5,
  2,
  428,
  7159,
  15135,
  47,
  288,
  4,
  5436,
  51,
  5,
  3814],
 [2,
  455,
  533,
  5,
  694,
  403,
  8,
  34,
  2,
  4895,
  880,
  263,
  51,
  3,
  5437,
  6,
  10818,
  13,
  4,
  35,
  445],
 [59,
  11,
  504,
  14,
  72,
  2,
  80,
  235,
  186,
  7,
  2,
  884,
  11,
  22,
  272,
  13,
  4,
  7160,
  234,
  1261,
  166,
  11,
  958,
  453,
  97,
  107],
 [29, 53, 18, 451],
 [10819,
  10820,
  16,
  4139,
  7,
  2,
  8495,
  6,
  15136,
  2948,
  10,
  6174,
  521,
  6,
  8528,
  2,
  10819],
 [14,
  308,
  2062,
  10821,
  34,
  541,
  3128,
  3,
  178,
  149,
  2,
  15137,
  9,
  33,
  78,
  180,
  8529,
  20,
  4,
  340,
  2799,
  265,
  166,
  228],
 [15138,
  645,
  214,
  9,
  82,
  10822,
  914,
  85,
  277,
  456,
  3,
  1417,
  4140,
  2642,
  577,
  72,
  348],
 [98, 529, 370, 3, 1487, 41, 915, 85, 8530, 7, 4, 3109, 2140, 1552, 20, 2348],
 [4896,
  15139,
  22,
  26,
  251,
  3,
  433,
  1127,
  2432,
  49,
  78,
  386,
  15140,
  125,
  4897,
  20,
  8531,
  2432,
  1591,
  7,
  996,
  8532,
  1823],
 [10823,
  70,
  8,
  459,
  677,
  68,
  6,
  7,
  28,
  1331,
  14,
  8,
  2,
  119,
  51,
  3,
  239,
  6,
  972,
  1417,
  1370,
  5,
  1418,
  1189,
  108,
  16,
  61,
  5,
  28,
  15141,
  7161,
  3,
  2800,
  12,
  800],
 [2, 357, 2656, 201, 3, 2, 310, 3333, 516],
 [384, 191, 4, 4461, 15142, 1224, 6, 197, 1902, 1985],

In [20]:
data[0]

[39,
 48,
 7,
 318,
 53,
 18,
 485,
 55,
 582,
 46,
 1690,
 10,
 446,
 1446,
 110,
 8479,
 300,
 3,
 582,
 46,
 1690,
 10,
 31,
 547,
 9,
 89,
 26,
 21,
 1582,
 4864]

In [21]:
input_sentances=[]
for sent in data:
    if len(sent)<2:
        continue
    for i in range(1,len(sent)):
        ngram=sent[:i+1]
        input_sentances.append(ngram)

In [22]:
input_sentances

[[39, 48],
 [39, 48, 7],
 [39, 48, 7, 318],
 [39, 48, 7, 318, 53],
 [39, 48, 7, 318, 53, 18],
 [39, 48, 7, 318, 53, 18, 485],
 [39, 48, 7, 318, 53, 18, 485, 55],
 [39, 48, 7, 318, 53, 18, 485, 55, 582],
 [39, 48, 7, 318, 53, 18, 485, 55, 582, 46],
 [39, 48, 7, 318, 53, 18, 485, 55, 582, 46, 1690],
 [39, 48, 7, 318, 53, 18, 485, 55, 582, 46, 1690, 10],
 [39, 48, 7, 318, 53, 18, 485, 55, 582, 46, 1690, 10, 446],
 [39, 48, 7, 318, 53, 18, 485, 55, 582, 46, 1690, 10, 446, 1446],
 [39, 48, 7, 318, 53, 18, 485, 55, 582, 46, 1690, 10, 446, 1446, 110],
 [39, 48, 7, 318, 53, 18, 485, 55, 582, 46, 1690, 10, 446, 1446, 110, 8479],
 [39,
  48,
  7,
  318,
  53,
  18,
  485,
  55,
  582,
  46,
  1690,
  10,
  446,
  1446,
  110,
  8479,
  300],
 [39,
  48,
  7,
  318,
  53,
  18,
  485,
  55,
  582,
  46,
  1690,
  10,
  446,
  1446,
  110,
  8479,
  300,
  3],
 [39,
  48,
  7,
  318,
  53,
  18,
  485,
  55,
  582,
  46,
  1690,
  10,
  446,
  1446,
  110,
  8479,
  300,
  3,
  582],
 [39,
  48,
  7,
  318,
  53,
  18,
  485,
  55,
  582,
  46,
  1690,
  10,
  446,
  1446,
  110,
  8479,
  300,
  3,
  582,
  46],
 [39,
  48,
  7,
  318,
  53,
  18,
  485,
  55,
  582,
  46,
  1690,
  10,
  446,
  1446,
  110,
  8479,
  300,
  3,
  582,
  46,
  1690],
 [39,
  48,
  7,
  318,
  53,
  18,
  485,
  55,
  582,
  46,
  1690,
  10,
  446,
  1446,
  110,
  8479,
  300,
  3,
  582,
  46,
  1690,
  10],
 [39,
  48,
  7,
  318,
  53,
  18,
  485,
  55,
  582,
  46,
  1690,
  10,
  446,
  1446,
  110,
  8479,
  300,
  3,
  582,
  46,
  1690,
  10,
  31],
 [39,
  48,
  7,
  318,
  53,
  18,
  485,
  55,
  582,
  46,
  1690,
  10,
  446,
  1446,
  110,
  8479,
  300,
  3,
  582,
  46,
  1690,
  10,
  31,
  547],
 [39,
  48,
  7,
  318,
  53,
  18,
  485,
  55,
  582,
  46,
  1690,
  10,
  446,
  1446,
  110,
  8479,
  300,
  3,
  582,
  46,
  1690,
  10,
  31,
  547,
  9],
 [39,
  48,
  7,
  318,
  53,
  18,
  485,
  55,
  582,
  46,
  1690,
  10,
  446,
  1446,
  110,
  8479,
  300,
  3,
  582,
  46,
  1690,
  10,
  31,
  547,
  9,
  89],
 [39,
  48,
  7,
  318,
  53,
  18,
  485,
  55,
  582,
  46,
  1690,
  10,
  446,
  1446,
  110,
  8479,
  300,
  3,
  582,
  46,
  1690,
  10,
  31,
  547,
  9,
  89,
  26],
 [39,
  48,
  7,
  318,
  53,
  18,
  485,
  55,
  582,
  46,
  1690,
  10,
  446,
  1446,
  110,
  8479,
  300,
  3,
  582,
  46,
  1690,
  10,
  31,
  547,
  9,
  89,
  26,
  21],
 [39,
  48,
  7,
  318,
  53,
  18,
  485,
  55,
  582,
  46,
  1690,
  10,
  446,
  1446,
  110,
  8479,
  300,
  3,
  582,
  46,
  1690,
  10,
  31,
  547,
  9,
  89,
  26,
  21,
  1582],
 [39,
  48,
  7,
  318,
  53,
  18,
  485,
  55,
  582,
  46,
  1690,
  10,
  446,
  1446,
  110,
  8479,
  300,
  3,
  582,
  46,
  1690,
  10,
  31,
  547,
  9,
  89,
  26,
  21,
  1582,
  4864],
 [14, 138],
 [14, 138, 21],
 [14, 138, 21, 60],
 [14, 138, 21, 60, 4],
 [14, 138, 21, 60, 4, 4445],
 [14, 138, 21, 60, 4, 4445, 115],
 [14, 138, 21, 60, 4, 4445, 115, 10],
 [14, 138, 21, 60, 4, 4445, 115, 10, 8480],
 [14, 138, 21, 60, 4, 4445, 115, 10, 8480, 781],
 [14, 138, 21, 60, 4, 4445, 115, 10, 8480, 781, 1017],
 [14, 138, 21, 60, 4, 4445, 115, 10, 8480, 781, 1017, 2785],
 [14, 138, 21, 60, 4, 4445, 115, 10, 8480, 781, 1017, 2785, 7128],
 [14, 138, 21, 60, 4, 4445, 115, 10, 8480, 781, 1017, 2785, 7128, 44],
 [14, 138, 21, 60, 4, 4445, 115, 10, 8480, 781, 1017, 2785, 7128, 44, 8481],
 [14,
  138,
  21,
  60,
  4,
  4445,
  115,
  10,
  8480,
  781,
  1017,
  2785,
  7128,
  44,
  8481,
  8482],
 [14,
  138,
  21,
  60,
  4,
  4445,
  115,
  10,
  8480,
  781,
  1017,
  2785,
  7128,
  44,
  8481,
  8482,
  10762],
 [14,
  138,
  21,
  60,
  4,
  4445,
  115,
  10,
  8480,
  781,
  1017,
  2785,
  7128,
  44,
  8481,
  8482,
  10762,
  795],
 [14,
  138,
  21,
  60,
  4,
  4445,
  115,
  10,
  8480,
  781,
  1017,
  2785,
  7128,
  44,
  8481,
  8482,
  10762,
  795,
  809],
 [4, 164],
 [4, 164, 1966],
 [4, 164, 1966, 50],
 [4, 164, 1966, 50, 2128],
 [4, 164, 1966, 50, 2128, 3],
 [4, 164, 1966, 50, 2128, 3, 474],
 [4, 164, 1966, 50, 2128, 3, 474, 2786],
 [4, 164, 1966, 50, 2128, 3, 474, 2786, 25],
 [4, 164, 1966, 50, 2128, 3, 474, 2786, 25, 2],
 [4, 164, 1966, 50, 2128, 3, 474, 2786, 25, 2, 1324],
 [4, 164, 1966, 50, 2128, 3, 474, 2786, 25, 2, 1324, 809],
 [1286, 319],
 [1286, 319, 79],
 [1286, 319, 79, 48],
 [1286, 319, 79, 48, 1121],
 [1286, 319, 79, 48, 1121, 1367],
 [1286, 319, 79, 48, 1121, 1367, 9],
 [1286, 319, 79, 48, 1121, 1367, 9, 397],
 [1286, 319, 79, 48, 1121, 1367, 9, 397, 20],
 [1286, 319, 79, 48, 1121, 1367, 9, 397, 20, 142],
 [1286, 319, 79, 48, 1121, 1367, 9, 397, 20, 142, 23],
 [1286, 319, 79, 48, 1121, 1367, 9, 397, 20, 142, 23, 7],
 [1286, 319, 79, 48, 1121, 1367, 9, 397, 20, 142, 23, 7, 2],
 [1286, 319, 79, 48, 1121, 1367, 9, 397, 20, 142, 23, 7, 2, 101],
 [1286, 319, 79, 48, 1121, 1367, 9, 397, 20, 142, 23, 7, 2, 101, 608],
 [1286, 319, 79, 48, 1121, 1367, 9, 397, 20, 142, 23, 7, 2, 101, 608, 83],
 [1286,
  319,
  79,
  48,
  1121,
  1367,
  9,
  397,
  20,
  142,
  23,
  7,
  2,
  101,
  608,
  83,
  1486],
 [1286,
  319,
  79,
  48,
  1121,
  1367,
  9,
  397,
  20,
  142,
  23,
  7,
  2,
  101,
  608,
  83,
  1486,
  2940],
 [1286,
  319,
  79,
  48,
  1121,
  1367,
  9,
  397,
  20,
  142,
  23,
  7,
  2,
  101,
  608,
  83,
  1486,
  2940,
  184],
 [1286,
  319,
  79,
  48,
  1121,
  1367,
  9,
  397,
  20,
  142,
  23,
  7,
  2,
  101,
  608,
  83,
  1486,
  2940,
  184,
  1368],
 [1286,
  319,
  79,
  48,
  1121,
  1367,
  9,
  397,
  20,
  142,
  23,
  7,
  2,
  101,
  608,
  83,
  1486,
  2940,
  184,
  1368,
  6],
 [1286,
  319,
  79,
  48,
  1121,
  1367,
  9,
  397,
  20,
  142,
  23,
  7,
  2,
  101,
  608,
  83,
  1486,
  2940,
  184,
  1368,
  6,
  796],
 [108, 16],
 [108, 16, 268],
 [108, 16, 268, 300],
 [108, 16, 268, 300, 3],
 [108, 16, 268, 300, 3, 71],
 [108, 16, 268, 300, 3, 71, 61],
 [108, 16, 268, 300, 3, 71, 61, 592],
 [108, 16, 268, 300, 3, 71, 61, 592, 374],
 [108, 16, 268, 300, 3, 71, 61, 592, 374, 105],
 [108, 16, 268, 300, 3, 71, 61, 592, 374, 105, 4865],
 [108, 16, 268, 300, 3, 71, 61, 592, 374, 105, 4865, 4],
 [108, 16, 268, 300, 3, 71, 61, 592, 374, 105, 4865, 4, 10763],
 [108, 16, 268, 300, 3, 71, 61, 592, 374, 105, 4865, 4, 10763, 10],
 [108, 16, 268, 300, 3, 71, 61, 592, 374, 105, 4865, 4, 10763, 10, 24],
 [108, 16, 268, 300, 3, 71, 61, 592, 374, 105, 4865, 4, 10763, 10, 24, 229],
 [10, 4],
 [10, 4, 259],
 [10, 4, 259, 241],
 [10, 4, 259, 241, 225],
 [10, 4, 259, 241, 225, 963],
 [10, 4, 259, 241, 225, 963, 6],
 [10, 4, 259, 241, 225, 963, 6, 241],
 [10, 4, 259, 241, 225, 963, 6, 241, 24],
 [10, 4, 259, 241, 225, 963, 6, 241, 24, 287],
 [10, 4, 259, 241, 225, 963, 6, 241, 24, 287, 4866],
 [10, 4, 259, 241, 225, 963, 6, 241, 24, 287, 4866, 34],
 [10, 4, 259, 241, 225, 963, 6, 241, 24, 287, 4866, 34, 39],
 [10, 4, 259, 241, 225, 963, 6, 241, 24, 287, 4866, 34, 39, 384],
 [10, 4, 259, 241, 225, 963, 6, 241, 24, 287, 4866, 34, 39, 384, 60],
 [10, 4, 259, 241, 225, 963, 6, 241, 24, 287, 4866, 34, 39, 384, 60, 4],
 [10, 4, 259, 241, 225, 963, 6, 241, 24, 287, 4866, 34, 39, 384, 60, 4, 187],
 [10,
  4,
  259,
  241,
  225,
  963,
  6,
  241,
  24,
  287,
  4866,
  34,
  39,
  384,
  60,
  4,
  187,
  5],
 [10,
  4,
  259,
  241,
  225,
  963,
  6,
  241,
  24,
  287,
  4866,
  34,
  39,
  384,
  60,
  4,
  187,
  5,
  19],
 [10,
  4,
  259,
  241,
  225,
  963,
  6,
  241,
  24,
  287,
  4866,
  34,
  39,
  384,
  60,
  4,
  187,
  5,
  19,
  69],
 [10,
  4,
  259,
  241,
  225,
  963,
  6,
  241,
  24,
  287,
  4866,
  34,
  39,
  384,
  60,
  4,
  187,
  5,
  19,
  69,
  40],
 [10,
  4,
  259,
  241,
  225,
  963,
  6,
  241,
  24,
  287,
  4866,
  34,
  39,
  384,
  60,
  4,
  187,
  5,
  19,
  69,
  40,
  5],
 [10,
  4,
  259,
  241,
  225,
  963,
  6,
  241,
  24,
  287,
  4866,
  34,
  39,
  384,
  60,
  4,
  187,
  5,
  19,
  69,
  40,
  5,
  82],
 [10,
  4,
  259,
  241,
  225,
  963,
  6,
  241,
  24,
  287,
  4866,
  34,
  39,
  384,
  60,
  4,
  187,
  5,
  19,
  69,
  40,
  5,
  82,
  128],
 [10,
  4,
  259,
  241,
  225,
  963,
  6,
  241,
  24,
  287,
  4866,
  34,
  39,
  384,
  60,
  4,
  187,
  5,
  19,
  69,
  40,
  5,
  82,
  128,
  6],
 [10,
  4,
  259,
  241,
  225,
  963,
  6,
  241,
  24,
  287,
  4866,
  34,
  39,
  384,
  60,
  4,
  187,
  5,
  19,
  69,
  40,
  5,
  82,
  128,
  6,
  35],
 [10,
  4,
  259,
  241,
  225,
  963,
  6,
  241,
  24,
  287,
  4866,
  34,
  39,
  384,
  60,
  4,
  187,
  5,
  19,
  69,
  40,
  5,
  82,
  128,
  6,
  35,
  16],
 [10,
  4,
  259,
  241,
  225,
  963,
  6,
  241,
  24,
  287,
  4866,
  34,
  39,
  384,
  60,
  4,
  187,
  5,
  19,
  69,
  40,
  5,
  82,
  128,
  6,
  35,
  16,
  128],
 [10,
  4,
  259,
  241,
  225,
  963,
  6,
  241,
  24,
  287,
  4866,
  34,
  39,
  384,
  60,
  4,
  187,
  5,
  19,
  69,
  40,
  5,
  82,
  128,
  6,
  35,
  16,
  128,
  9],
 [10,
  4,
  259,
  241,
  225,
  963,
  6,
  241,
  24,
  287,
  4866,
  34,
  39,
  384,
  60,
  4,
  187,
  5,
  19,
  69,
  40,
  5,
  82,
  128,
  6,
  35,
  16,
  128,
  9,
  93],
 [10,
  4,
  259,
  241,
  225,
  963,
  6,
  241,
  24,
  287,
  4866,
  34,
  39,
  384,
  60,
  4,
  187,
  5,
  19,
  69,
  40,
  5,
  82,
  128,
  6,
  35,
  16,
  128,
  9,
  93,
  672],
 [10,
  4,
  259,
  241,
  225,
  963,
  6,
  241,
  24,
  287,
  4866,
  34,
  39,
  384,
  60,
  4,
  187,
  5,
  19,
  69,
  40,
  5,
  82,
  128,
  6,
  35,
  16,
  128,
  9,
  93,
  672,
  12],
 [10,
  4,
  259,
  241,
  225,
  963,
  6,
  241,
  24,
  287,
  4866,
  34,
  39,
  384,
  60,
  4,
  187,
  5,
  19,
  69,
  40,
  5,
  82,
  128,
  6,
  35,
  16,
  128,
  9,
  93,
  672,
  12,
  30],
 [10,
  4,
  259,
  241,
  225,
  963,
  6,
  241,
  24,
  287,
  4866,
  34,
  39,
  384,
  60,
  4,
  187,
  5,
  19,
  69,
  40,
  5,
  82,
  128,
  6,
  35,
  16,
  128,
  9,
  93,
  672,
  12,
  30,
  537],
 [10,
  4,
  259,
  241,
  225,
  963,
  6,
  241,
  24,
  287,
  4866,
  34,
  39,
  384,
  60,
  4,
  187,
  5,
  19,
  69,
  40,
  5,
  82,
  128,
  6,
  35,
  16,
  128,
  9,
  93,
  672,
  12,
  30,
  537,
  3],
 [10,
  4,
  259,
  241,
  225,
  963,
  6,
  241,
  24,
  287,
  4866,
  34,
  39,
  384,
  60,
  4,
  187,
  5,
  19,
  69,
  40,
  5,
  82,
  128,
  6,
  35,
  16,
  128,
  9,
  93,
  672,
  12,
  30,
  537,
  3,
  1487],
 [10,
  4,
  259,
  241,
  225,
  963,
  6,
  241,
  24,
  287,
  4866,
  34,
  39,
  384,
  60,
  4,
  187,
  5,
  19,
  69,
  40,
  5,
  82,
  128,
  6,
  35,
  16,
  128,
  9,
  93,
  672,
  12,
  30,
  537,
  3,
  1487,
  24],
 [10,
  4,
  259,
  241,
  225,
  963,
  6,
  241,
  24,
  287,
  4866,
  34,
  39,
  384,
  60,
  4,
  187,
  5,
  19,
  69,
  40,
  5,
  82,
  128,
  6,
  35,
  16,
  128,
  9,
  93,
  672,
  12,
  30,
  537,
  3,
  1487,
  24,
  1447],
 [32, 810],
 [32, 810, 15034],
 [32, 810, 15034, 15035],
 [32, 810, 15034, 15035, 3787],
 [32, 810, 15034, 15035, 3787, 4446],
 [32, 810, 15034, 15035, 3787, 4446, 39],
 [32, 810, 15034, 15035, 3787, 4446, 39, 73],
 [32, 810, 15034, 15035, 3787, 4446, 39, 73, 14],
 [32, 810, 15034, 15035, 3787, 4446, 39, 73, 14, 111],
 [32, 810, 15034, 15035, 3787, 4446, 39, 73, 14, 111, 3],
 [32, 810, 15034, 15035, 3787, 4446, 39, 73, 14, 111, 3, 582],
 [32, 810, 15034, 15035, 3787, 4446, 39, 73, 14, 111, 3, 582, 4],
 [32, 810, 15034, 15035, 3787, 4446, 39, 73, 14, 111, 3, 582, 4, 35],
 [32, 810, 15034, 15035, 3787, 4446, 39, 73, 14, 111, 3, 582, 4, 35, 782],
 [32,
  810,
  15034,
  15035,
  3787,
  4446,
  39,
  73,
  14,
  111,
  3,
  582,
  4,
  35,
  782,
  5403],
 [32,
  810,
  15034,
  15035,
  3787,
  4446,
  39,
  73,
  14,
  111,
  3,
  582,
  4,
  35,
  782,
  5403,
  3109],
 [32,
  810,
  15034,
  15035,
  3787,
  4446,
  39,
  73,
  14,
  111,
  3,
  582,
  4,
  35,
  782,
  5403,
  3109,
  39],
 [32,
  810,
  15034,
  15035,
  3787,
  4446,
  39,
  73,
  14,
  111,
  3,
  582,
  4,
  35,
  782,
  5403,
  3109,
  39,
  2941],
 [32,
  810,
  15034,
  15035,
  3787,
  4446,
  39,
  73,
  14,
  111,
  3,
  582,
  4,
  35,
  782,
  5403,
  3109,
  39,
  2941,
  269],
 [7, 1122],
 [7, 1122, 10764],
 [7, 1122, 10764, 10765],
 [7, 1122, 10764, 10765, 2],
 [7, 1122, 10764, 10765, 2, 86],
 [7, 1122, 10764, 10765, 2, 86, 2],
 [7, 1122, 10764, 10765, 2, 86, 2, 991],
 [7, 1122, 10764, 10765, 2, 86, 2, 991, 314],
 [7, 1122, 10764, 10765, 2, 86, 2, 991, 314, 3],
 [7, 1122, 10764, 10765, 2, 86, 2, 991, 314, 3, 623],
 [7, 1122, 10764, 10765, 2, 86, 2, 991, 314, 3, 623, 54],
 [7, 1122, 10764, 10765, 2, 86, 2, 991, 314, 3, 623, 54, 52],
 [7, 1122, 10764, 10765, 2, 86, 2, 991, 314, 3, 623, 54, 52, 38],
 [7, 1122, 10764, 10765, 2, 86, 2, 991, 314, 3, 623, 54, 52, 38, 43],
 [7, 1122, 10764, 10765, 2, 86, 2, 991, 314, 3, 623, 54, 52, 38, 43, 85],
 [7, 1122, 10764, 10765, 2, 86, 2, 991, 314, 3, 623, 54, 52, 38, 43, 85, 139],
 [7,
  1122,
  10764,
  10765,
  2,
  86,
  2,
  991,
  314,
  3,
  623,
  54,
  52,
  38,
  43,
  85,
  139,
  43],
 [7,
  1122,
  10764,
  10765,
  2,
  86,
  2,
  991,
  314,
  3,
  623,
  54,
  52,
  38,
  43,
  85,
  139,
  43,
  73],
 [7,
  1122,
  10764,
  10765,
  2,
  86,
  2,
  991,
  314,
  3,
  623,
  54,
  52,
  38,
  43,
  85,
  139,
  43,
  73,
  4112],
 [7,
  1122,
  10764,
  10765,
  2,
  86,
  2,
  991,
  314,
  3,
  623,
  54,
  52,
  38,
  43,
  85,
  139,
  43,
  73,
  4112,
  42],
 [7,
  1122,
  10764,
  10765,
  2,
  86,
  2,
  991,
  314,
  3,
  623,
  54,
  52,
  38,
  43,
  85,
  139,
  43,
  73,
  4112,
  42,
  3543],
 [38, 11],
 [38, 11, 22],
 [38, 11, 22, 4],
 [38, 11, 22, 4, 878],
 [38, 11, 22, 4, 878, 701],
 [38, 11, 22, 4, 878, 701, 52],
 [38, 11, 22, 4, 878, 701, 52, 7],
 [38, 11, 22, 4, 878, 701, 52, 7, 482],
 [38, 11, 22, 4, 878, 701, 52, 7, 482, 564],
 [38, 11, 22, 4, 878, 701, 52, 7, 482, 564, 783],
 [38, 11, 22, 4, 878, 701, 52, 7, 482, 564, 783, 182],
 [38, 11, 22, 4, 878, 701, 52, 7, 482, 564, 783, 182, 2],
 [38, 11, 22, 4, 878, 701, 52, 7, 482, 564, 783, 182, 2, 6135],
 [38, 11, 22, 4, 878, 701, 52, 7, 482, 564, 783, 182, 2, 6135, 28],
 [38, 11, 22, 4, 878, 701, 52, 7, 482, 564, 783, 182, 2, 6135, 28, 98],
 [38, 11, 22, 4, 878, 701, 52, 7, 482, 564, 783, 182, 2, 6135, 28, 98, 338],
 [38,
  11,
  22,
  4,
  878,
  701,
  52,
  7,
  482,
  564,
  783,
  182,
  2,
  6135,
  28,
  98,
  338,
  828],
 [38,
  11,
  22,
  4,
  878,
  701,
  52,
  7,
  482,
  564,
  783,
  182,
  2,
  6135,
  28,
  98,
  338,
  828,
  3],
 [38,
  11,
  22,
  4,
  878,
  701,
  52,
  7,
  482,
  564,
  783,
  182,
  2,
  6135,
  28,
  98,
  338,
  828,
  3,
  766],
 [38,
  11,
  22,
  4,
  878,
  701,
  52,
  7,
  482,
  564,
  783,
  182,
  2,
  6135,
  28,
  98,
  338,
  828,
  3,
  766,
  85],
 [38,
  11,
  22,
  4,
  878,
  701,
  52,
  7,
  482,
  564,
  783,
  182,
  2,
  6135,
  28,
  98,
  338,
  828,
  3,
  766,
  85,
  2],
 [38,
  11,
  22,
  4,
  878,
  701,
  52,
  7,
  482,
  564,
  783,
  182,
  2,
  6135,
  28,
  98,
  338,
  828,
  3,
  766,
  85,
  2,
  15036],
 [38,
  11,
  22,
  4,
  878,
  701,
  52,
  7,
  482,
  564,
  783,
  182,
  2,
  6135,
  28,
  98,
  338,
  828,
  3,
  766,
  85,
  2,
  15036,
  6],
 [49, 63],
 [49, 63, 19],
 [49, 63, 19, 176],
 [49, 63, 19, 176, 8],
 [49, 63, 19, 176, 8, 7],
 [49, 63, 19, 176, 8, 7, 4],
 [49, 63, 19, 176, 8, 7, 4, 220],
 [49, 63, 19, 176, 8, 7, 4, 220, 2641],
 [15037, 6],
 [15037, 6, 15038],
 [15037, 6, 15038, 263],
 [15037, 6, 15038, 263, 2129],
 [15037, 6, 15038, 263, 2129, 5],
 [15037, 6, 15038, 263, 2129, 5, 19],
 [15037, 6, 15038, 263, 2129, 5, 19, 415],
 [15037, 6, 15038, 263, 2129, 5, 19, 415, 7],
 [15037, 6, 15038, 263, 2129, 5, 19, 415, 7, 6136],
 [15037, 6, 15038, 263, 2129, 5, 19, 415, 7, 6136, 22],
 [15037, 6, 15038, 263, 2129, 5, 19, 415, 7, 6136, 22, 28],
 [15037, 6, 15038, 263, 2129, 5, 19, 415, 7, 6136, 22, 28, 423],
 [15037, 6, 15038, 263, 2129, 5, 19, 415, 7, 6136, 22, 28, 423, 1967],
 [15037, 6, 15038, 263, 2129, 5, 19, 415, 7, 6136, 22, 28, 423, 1967, 6137],
 [15037,
  6,
  15038,
  263,
  2129,
  5,
  19,
  415,
  7,
  6136,
  22,
  28,
  423,
  1967,
  6137,
  8483],
 [15037,
  6,
  15038,
  263,
  2129,
  5,
  19,
  415,
  7,
  6136,
  22,
  28,
  423,
  1967,
  6137,
  8483,
  63],
 [964, 300],
 [964, 300, 3],
 [964, 300, 3, 131],
 [964, 300, 3, 131, 965],
 [964, 300, 3, 131, 965, 13],
 [964, 300, 3, 131, 965, 13, 24],
 [964, 300, 3, 131, 965, 13, 24, 952],
 [964, 300, 3, 131, 965, 13, 24, 952, 4867],
 [964, 300, 3, 131, 965, 13, 24, 952, 4867, 7129],
 [964, 300, 3, 131, 965, 13, 24, 952, 4867, 7129, 37],
 [964, 300, 3, 131, 965, 13, 24, 952, 4867, 7129, 37, 965],
 [964, 300, 3, 131, 965, 13, 24, 952, 4867, 7129, 37, 965, 4],
 [964, 300, 3, 131, 965, 13, 24, 952, 4867, 7129, 37, 965, 4, 199],
 [964, 300, 3, 131, 965, 13, 24, 952, 4867, 7129, 37, 965, 4, 199, 5],
 [964, 300, 3, 131, 965, 13, 24, 952, 4867, 7129, 37, 965, 4, 199, 5, 51],
 [964, 300, 3, 131, 965, 13, 24, 952, 4867, 7129, 37, 965, 4, 199, 5, 51, 6],
 [964,
  300,
  3,
  131,
  965,
  13,
  24,
  952,
  4867,
  7129,
  37,
  965,
  4,
  199,
  5,
  51,
  6,
  652],
 [964,
  300,
  3,
  131,
  965,
  13,
  24,
  952,
  4867,
  7129,
  37,
  965,
  4,
  199,
  5,
  51,
  6,
  652,
  38],
 [964,
  300,
  3,
  131,
  965,
  13,
  24,
  952,
  4867,
  7129,
  37,
  965,
  4,
  199,
  5,
  51,
  6,
  652,
  38,
  4868],
 [964,
  300,
  3,
  131,
  965,
  13,
  24,
  952,
  4867,
  7129,
  37,
  965,
  4,
  199,
  5,
  51,
  6,
  652,
  38,
  4868,
  24],
 [964,
  300,
  3,
  131,
  965,
  13,
  24,
  952,
  4867,
  7129,
  37,
  965,
  4,
  199,
  5,
  51,
  6,
  652,
  38,
  4868,
  24,
  952],
 [964,
  300,
  3,
  131,
  965,
  13,
  24,
  952,
  4867,
  7129,
  37,
  965,
  4,
  199,
  5,
  51,
  6,
  652,
  38,
  4868,
  24,
  952,
  5404],
 [964,
  300,
  3,
  131,
  965,
  13,
  24,
  952,
  4867,
  7129,
  37,
  965,
  4,
  199,
  5,
  51,
  6,
  652,
  38,
  4868,
  24,
  952,
  5404,
  111],
 [964,
  300,
  3,
  131,
  965,
  13,
  24,
  952,
  4867,
  7129,
  37,
  965,
  4,
  199,
  5,
  51,
  6,
  652,
  38,
  4868,
  24,
  952,
  5404,
  111,
  2],
 [964,
  300,
  3,
  131,
  965,
  13,
  24,
  952,
  4867,
  7129,
  37,
  965,
  4,
  199,
  5,
  51,
  6,
  652,
  38,
  4868,
  24,
  952,
  5404,
  111,
  2,
  51],
 [964,
  300,
  3,
  131,
  965,
  13,
  24,
  952,
  4867,
  7129,
  37,
  965,
  4,
  199,
  5,
  51,
  6,
  652,
  38,
  4868,
  24,
  952,
  5404,
  111,
  2,
  51,
  3],
 [964,
  300,
  3,
  131,
  965,
  13,
  24,
  952,
  4867,
  7129,
  37,
  965,
  4,
  199,
  5,
  51,
  6,
  652,
  38,
  4868,
  24,
  952,
  5404,
  111,
  2,
  51,
  3,
  7130],
 [964,
  300,
  3,
  131,
  965,
  13,
  24,
  952,
  4867,
  7129,
  37,
  965,
  4,
  199,
  5,
  51,
  6,
  652,
  38,
  4868,
  24,
  952,
  5404,
  111,
  2,
  51,
  3,
  7130,
  82],
 [964,
  300,
  3,
  131,
  965,
  13,
  24,
  952,
  4867,
  7129,
  37,
  965,
  4,
  199,
  5,
  51,
  6,
  652,
  38,
  4868,
  24,
  952,
  5404,
  111,
  2,
  51,
  3,
  7130,
  82,
  2642],
 [964,
  300,
  3,
  131,
  965,
  13,
  24,
  952,
  4867,
  7129,
  37,
  965,
  4,
  199,
  5,
  51,
  6,
  652,
  38,
  4868,
  24,
  952,
  5404,
  111,
  2,
  51,
  3,
  7130,
  82,
  2642,
  6138],
 [964,
  300,
  3,
  131,
  965,
  13,
  24,
  952,
  4867,
  7129,
  37,
  965,
  4,
  199,
  5,
  51,
  6,
  652,
  38,
  4868,
  24,
  952,
  5404,
  111,
  2,
  51,
  3,
  7130,
  82,
  2642,
  6138,
  7129],
 [964,
  300,
  3,
  131,
  965,
  13,
  24,
  952,
  4867,
  7129,
  37,
  965,
  4,
  199,
  5,
  51,
  6,
  652,
  38,
  4868,
  24,
  952,
  5404,
  111,
  2,
  51,
  3,
  7130,
  82,
  2642,
  6138,
  7129,
  1817],
 [45, 3788],
 [45, 3788, 2],
 [45, 3788, 2, 80],
 [45, 3788, 2, 80, 51],
 [45, 3788, 2, 80, 51, 9],
 [45, 3788, 2, 80, 51, 9, 61],
 [45, 3788, 2, 80, 51, 9, 61, 1018],
 [45, 3788, 2, 80, 51, 9, 61, 1018, 29],
 [45, 3788, 2, 80, 51, 9, 61, 1018, 29, 1018],
 [45, 3788, 2, 80, 51, 9, 61, 1018, 29, 1018, 1488],
 [45, 3788, 2, 80, 51, 9, 61, 1018, 29, 1018, 1488, 7],

In [23]:
max_len=max([len(i) for i in input_sentances])

In [24]:
max_len

167

In [25]:
input=pad_sequences(input_sentances,padding='pre',maxlen=max_len)

In [26]:
input

array([[  0,   0,   0, ...,   0,  39,  48],
       [  0,   0,   0, ...,  39,  48,   7],
       [  0,   0,   0, ...,  48,   7, 318],
       ...,
       [  0,   0,   0, ...,   6, 609,  12],
       [  0,   0,   0, ..., 609,  12, 100],
       [  0,   0,   0, ...,  12, 100, 116]],
      shape=(375340, 167), dtype=int32)

In [27]:
input[1]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 39, 48,  7],
      dtype=int32)

In [28]:
input.shape

(375340, 167)

In [29]:
X=input[:,:-1]

In [30]:
X.shape

(375340, 166)

In [31]:
Y=input[:,-1]

In [32]:
Y

array([ 48,   7, 318, ...,  12, 100, 116], shape=(375340,), dtype=int32)

In [33]:
Y.shape

(375340,)

In [34]:
## Train Test split
from sklearn.model_selection import train_test_split

In [35]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [36]:
X_train.shape

(300272, 166)

In [37]:
max_len=X.shape[1]
max_len

166

In [38]:
vocab_size=len(tokenizer.word_index)+1

In [39]:
vocab_size

29283

In [40]:
model=Sequential([Embedding(vocab_size,128,input_length=max_len),LSTM(256),Dense(vocab_size,activation='softmax')])

c:\Users\tripa\OneDrive\Desktop\IIITR B.TECH\GEN-AI\4.Deep_Learning\venv\Lib\site-packages\keras\src\layers\core\embedding.py:123: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [42]:
model.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [43]:
model.build(input_shape=(None,max_len))

In [44]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 166, 128)       │     3,748,224 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 256)            │       394,240 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 29283)          │     7,525,731 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 11,668,195 (44.51 MB)

 Trainable params: 11,668,195 (44.51 MB)

 Non-trainable params: 0 (0.00 B)

In [45]:
model.fit(X_train,Y_train,validation_data=(X_test,Y_test),epochs=10)

Epoch 1/10
4729/9384 ━━━━━━━━━━━━━━━━━━━━ 34:40 447ms/step - accuracy: 0.0722 - loss: 7.3711

KeyboardInterrupt:

In [ ]:
model.save('Next_word_pred.h5')

In [ ]:
import pickle
with open('tokenizer.pkl','wb') as file:
    pickle.dump(tokenizer,file)

In [52]:
data2=pd.read_json("News_Category_Dataset_v3.json",lines=True)
data2

,link,headline,category,short_description,authors,date
0,https://www.huffpost.com/entry/covid-boosters-...,Over 4 Million Americans Roll Up Sleeves For O...,U.S. NEWS,Health experts said it is too early to predict...,"Carla K. Johnson, AP",2022-09-23
1,https://www.huffpost.com/entry/american-airlin...,"American Airlines Flyer Charged, Banned For Li...",U.S. NEWS,He was subdued by passengers and crew when he ...,Mary Papenfuss,2022-09-23
2,https://www.huffpost.com/entry/funniest-tweets...,23 Of The Funniest Tweets About Cats And Dogs ...,COMEDY,"""Until you have a dog you don't understand wha...",Elyse Wanshel,2022-09-23
3,https://www.huffpost.com/entry/funniest-parent...,The Funniest Tweets From Parents This Week (Se...,PARENTING,"""Accidentally put grown-up toothpaste on my to...",Caroline Bologna,2022-09-23
4,https://www.huffpost.com/entry/amy-cooper-lose...,Woman Who Called Cops On Black Bird-Watcher Lo...,U.S. NEWS,Amy Cooper accused investment firm Franklin Te...,Nina Golgowski,2022-09-22
...,...,...,...,...,...,...
209522,https://www.huffingtonpost.com/entry/rim-ceo-t...,RIM CEO Thorsten Heins' 'Significant' Plans Fo...,TECH,Verizon Wireless and AT&T are already promotin...,"Reuters, Reuters",2012-01-28
209523,https://www.huffingtonpost.com/entry/maria-sha...,Maria Sharapova Stunned By Victoria Azarenka I...,SPORTS,"Afterward, Azarenka, more effusive with the pr...",,2012-01-28
209524,https://www.huffingtonpost.com/entry/super-bow...,"Giants Over Patriots, Jets Over Colts Among M...",SPORTS,"Leading up to Super Bowl XLVI, the most talked...",,2012-01-28
209525,https://www.huffingtonpost.com/entry/aldon-smi...,Aldon Smith Arrested: 49ers Linebacker Busted ...,SPORTS,CORRECTION: An earlier version of this story i...,,2012-01-28
209526,https://www.huffingtonpost.com/entry/dwight-ho...,Dwight Howard Rips Teammates After Magic Loss ...,SPORTS,The five-time all-star center tore into his te...,,2012-01-28

In [53]:
data2=data2['short_description']

In [54]:
data2

0         Health experts said it is too early to predict...
1         He was subdued by passengers and crew when he ...
2         "Until you have a dog you don't understand wha...
3         "Accidentally put grown-up toothpaste on my to...
4         Amy Cooper accused investment firm Franklin Te...
                                ...
209522    Verizon Wireless and AT&T are already promotin...
209523    Afterward, Azarenka, more effusive with the pr...
209524    Leading up to Super Bowl XLVI, the most talked...
209525    CORRECTION: An earlier version of this story i...
209526    The five-time all-star center tore into his te...
Name: short_description, Length: 209527, dtype: str

In [55]:
df=pd.DataFrame(data2)

In [56]:
df

                                        short_description
0       Health experts said it is too early to predict...
1       He was subdued by passengers and crew when he ...
2       "Until you have a dog you don't understand wha...
3       "Accidentally put grown-up toothpaste on my to...
4       Amy Cooper accused investment firm Franklin Te...
...                                                   ...
209522  Verizon Wireless and AT&T are already promotin...
209523  Afterward, Azarenka, more effusive with the pr...
209524  Leading up to Super Bowl XLVI, the most talked...
209525  CORRECTION: An earlier version of this story i...
209526  The five-time all-star center tore into his te...

[209527 rows x 1 columns]

In [57]:
df.to_csv('data.csv')